In [ ]:
import numpy as num

Problem - 1: Array Creation:
Complete the following Tasks:
1.	Initialize an empty array with size 2X2.
2.	Initialize an all one array with size 4X2.
3.	Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4.	Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5.	Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6.	For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
import numpy as np
#Task 1
#Empty array 2x2
arr1 = np.empty((2, 2))
print("Empty:\n", arr1)

#All ones 4x2
arr2 = np.ones((4, 2))
print("\nOnes:\n", arr2)

#Fill with specific value 7
arr3 = np.full((2, 2), 7)
print("\nFilled with 7:\n", arr3)

#Zeros with same shape as arr2
arr4 = np.zeros_like(arr2)
print("\nZeros like arr2:\n", arr4)

#Ones with same shape as arr1
arr5 = np.ones_like(arr1)
print("\nOnes like arr1:\n", arr5)

#Convert list to array
my_list = [1, 2, 3, 4]
arr6 = np.array(my_list)

#Display result
print("\nList to Array:", arr6)



Empty:
 [[1.14e-322 2.52e-322]
 [6.42e-323 1.43e-322]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled with 7:
 [[7 7]
 [7 7]]

Zeros like arr2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like arr1:
 [[1. 1.]
 [1. 1.]]

List to Array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1.	Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2.	Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3.	Create a 3X3 identity matrix.{Hint:np.eye()}
4.	Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5.	Create a 10X10 array with random values and find the minimum and maximum values.
6.	Create a zero array of size 10 and replace 5th element with 1.
7.	Reverse an array arr = [1,2,0,0,4,0].
8.	Create a 2d array with 1 on border and 0 inside.
9.	Create a 8X8 matrix and fill it with a checkerboard pattern.


In [ ]:
#Task 2
#Range 10 to 49
task1 = np.arange(10, 50)
print("Range:", task1)

#3x3 Matrix with 0-8
task2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix:\n", task2)

#Identity Matrix
task3 = np.eye(3)
print("\nIdentity:\n", task3)

#Random array stats
task4 = np.random.random(30)
print(f"\nMean value: {task4.mean()}")

#Random 10x10 stats
task5 = np.random.random((10, 10))
print(f"\nMin: {task5.min()}, Max: {task5.max()}")

#Replace 5th element
task6 = np.zeros(10)
task6[4] = 1
print("\nreplaced 5th element:", task6)

#Reverse array
arr = np.array([1, 2, 0, 0, 4, 0])
task7 = arr[::-1]
print("\nReversed:", task7)

#Border of 1s, 0s inside
task8 = np.ones((5, 5))
task8[1:-1, 1:-1] = 0
print("\nBorder Pattern:\n", task8)

#Checkerboard Pattern
task9 = np.zeros((8, 8))
task9[1::2, ::2] = 1
task9[::2, 1::2] = 1


#Displaying result
print("\nCheckerboard:\n", task9)


Range: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean value: 0.5026937700642878

Min: 0.0001068403982231736, Max: 0.9799511031341651

replaced 5th element: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed: [0 4 0 0 2 1]

Border Pattern:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:
1.	Add the two array.
2.	Subtract the two array.
3.	Multiply the array with any integers of your choice.
4.	Find the square of each element of the array.
5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6.	Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [ ]:
#Task3
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#Add
print("Add:\n", x + y)

#Subtract
print("\nSubtract:\n", x - y)

#Multiply by integer
print("\nMultiply by 3:\n", x * 3)

#Square elements
print("\nSquare:\n", x ** 2)

#Dot Products
print("\nDot v,w:", np.dot(v, w))
print("Dot x,v:", np.dot(x, v))
print("Dot x,y:\n", np.dot(x, y))

#Concatenate
print("\nConcat rows:\n", np.concatenate((x, y), axis=0))
print("Concat cols:\n", np.column_stack((v, w)))

#Error Task
print("\nTrying to concat x and v:")
try:
    print(np.concatenate((x, v)))
except:
    print("Error: You cannot link a 2D matrix with a 1D vector directly.")

Add:
 [[ 6  8]
 [10 13]]

Subtract:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot v,w: 219
Dot x,v: [29 77]
Dot x,y:
 [[19 22]
 [50 58]]

Concat rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concat cols:
 [[ 9 11]
 [10 12]]

Trying to concat x and v:
Error: You cannot link a 2D matrix with a 1D vector directly.


Problem - 4: Matrix Operations: • For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:
1.	Prove A.A−1 = I.
2.	Prove AB ̸= BA.
3.	Prove (AB)T = BTAT.
•	Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1 x − y + 2z = −3 3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
•	Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}


In [ ]:
#Task4
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Linear Equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

#Prove Inverse
inv_A = np.linalg.inv(A)
print("A * Inv(A) (Should be Identity):\n", np.dot(A, inv_A).round())

#Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))

#Prove Transpose rule
print("\n(AB) Transpose matches B.T * A.T?", np.array_equal(AB.T, np.dot(B.T, A.T)))

coeffs = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
answers = np.array([-1, -3, 9])

#Solving
xyz = np.linalg.solve(coeffs, answers)

#Displaying result
print("\nSolution for x, y, z:", xyz)

A * Inv(A) (Should be Identity):
 [[1. 0.]
 [0. 1.]]

Is AB equal to BA? False

(AB) Transpose matches B.T * A.T? True

Solution for x, y, z: [ 2.  1. -2.]


Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
•	Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
2. Element-wise Multiplication
•	Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
3. Dot Product
•	Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
4. Matrix Multiplication
•	Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
•	Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [ ]:
#Task 5
import time

#Element-wise Addition
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
arr1 = np.arange(size)
arr2 = np.arange(size)

print("Addition (Size 1,000,000)")
#Python List
start = time.time()
res_list = [x + y for x, y in zip(list1, list2)]
print(f"Python List: {time.time() - start:.5f} seconds")

#Numpy
start = time.time()
res_arr = arr1 + arr2
print(f"Numpy Array: {time.time() - start:.5f} seconds")


#Element-wise Multiplication
print("\n2. Multiplication (Size 1,000,000)")

start = time.time()
res_list_mul = [x * y for x, y in zip(list1, list2)]
print(f"Python List: {time.time() - start:.5f} seconds")

#Numpy
start = time.time()
res_arr_mul = arr1 * arr2
print(f"Numpy Array: {time.time() - start:.5f} seconds")


#Dot Product
print("\n3. Dot Product (Size 1,000,000)")

start = time.time()
dot_list = sum([x * y for x, y in zip(list1, list2)])
print(f"Python List: {time.time() - start:.5f} seconds")

#Numpy
start = time.time()
dot_arr = np.dot(arr1, arr2)
print(f"Numpy Array: {time.time() - start:.5f} seconds")


#Matrix Multiplication

print("\n4. Matrix Multiplication")

#Setup for Python
mat_size_py = 1000
A_list = [[1 for _ in range(mat_size_py)] for _ in range(mat_size_py)]
B_list = [[1 for _ in range(mat_size_py)] for _ in range(mat_size_py)]
result_list = [[0 for _ in range(mat_size_py)] for _ in range(mat_size_py)]

start = time.time()
for i in range(mat_size_py):
    for j in range(mat_size_py):
        for k in range(mat_size_py):
            result_list[i][j] += A_list[i][k] * B_list[k][j]
print(f"Python List (1000x1000): {time.time() - start:.5f} seconds")

#Setup for Numpy
mat_size_np = 1000
A_np = np.ones((mat_size_np, mat_size_np))
B_np = np.ones((mat_size_np, mat_size_np))

start = time.time()
res_matmul = np.dot(A_np, B_np)
print(f"Numpy Array (1000x1000): {time.time() - start:.5f} seconds")

Addition (Size 1,000,000)
Python List: 0.05119 seconds
Numpy Array: 0.00195 seconds

2. Multiplication (Size 1,000,000)
Python List: 0.05012 seconds
Numpy Array: 0.00108 seconds

3. Dot Product (Size 1,000,000)
Python List: 0.05542 seconds
Numpy Array: 0.00085 seconds

4. Matrix Multiplication
Python List (1000x1000): 197.90104 seconds
Numpy Array (1000x1000): 0.05752 seconds
